version: '3.7'

services:
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:5000/weather
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/app
    dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/weatherdb
      - OPENWEATHERMAP_API_KEY=fec734c51bd96203d583749fb62d52e6
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weatherdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db_data:
