version: '3.7'

services:
  frontend:
    build: ./frontend/app
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:5000/weather
    depends_on:
      - backend

  backend:
    build: ./backend/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/weatherdb
      - OPENWEATHERMAP_API_KEY=fec734c51bd96203d583749fb62d52e6
    depends_on:
      - db

  db:
    build: ./db
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weatherdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

    frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
  ports:
    - "3000:80" # Map port 3000 on the host to port 80 in the container

volumes:
  db_data:
